manifest:
  remotes:
    - name: zmk-plover-hid
      url-base: https://github.com/phuertay
  projects:
    - name: zmk-plover-hid
      remote: zmk-plover-hid
      revision: main
      import: app/west.yml
  self:
    path: config
