manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/lazerwalker
  projects:
    - name: zmk-plover-hid
      remote: zmk
      revision: zmk/tree/plover-hid-hog-attempt
      import: app/west.yml
  self:
    path: config
