manifest:
  remotes:
    - name: ph
      url-base: https://github.com/phuertay
  projects:
    - name: zmk
      remote: ph
      revision: main
      import: app/west.yml
    - name: zmk-keyboard-dacman56
      remote: ph
      revision: main
  self:
    path: config
