manifest:
  remotes:
    - name: lazer
      url-base: https://github.com/lazerwalker/zmk
  projects:
    - name: zmk
      remote: lazer
      revision: plover-hid-hog-attempt
      import: app/west.yml
  self:
    path: config
