manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/lazerwalker/zmk
  projects:
    - name: plover
      remote: zmk
      revision: plover-hid-hog-attempt
      import: app/west.yml
  self:
    path: config
